project_id = "nvplotnfmirkqkpkzenw"

[functions.admin-create-user]
verify_jwt = false

[functions.admin-manage-user]
verify_jwt = false

[functions.verify-totp]
verify_jwt = false

[functions.geocode-zips]
verify_jwt = false